dist: xenial
language: generic
addons:
  apt:
    packages:
    - tor
    - torsocks
install:
- pip install --user waybackpack
- pip install --user pygments restructuredtext-lint
script:
- shellcheck waybackpack2git
- WAYBACKPACK2GIT_ONLINE_TESTS=1 torsocks prove -v
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
