#!/bin/sh

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u

if [ $# -lt 2 ]
then
    printf 'Usage: %s DSTDIR SRCDIR...\n' "${0##*/}" >&2
    exit 1
fi
dstdir="$1"
shift
for dir in "$@"
do
    base="$(basename "$dir")"
    case "$base" in
    [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]);;
    *)
        printf "%s: %s doesn't look like a waybackpack directory\n" "$0" "$dir"
        exit 1
    esac
done
mkdir "$dstdir"
git init "$dstdir"
for dir in "$@"
do
    base="$(basename "$dir")"
    date=$(printf '%s' "$base" | sed -n -E -e '/^(....)(..)(..)(..)(..)(..)$/ { s//\1-\2-\3 \4:\5:\6 UTC/; p; q }')
    dir="$(readlink -f "$dir")"
    git -C "$dstdir" config --replace-all core.worktree "$dir"
    git -C "$dstdir" add -A .
    git -C "$dstdir" commit --quiet -m '' --allow-empty-message --allow-empty --date "$date"
done
git -C "$dstdir" config --unset-all core.worktree
git -C "$dstdir" reset --hard master

# vim:ts=4 sts=4 sw=4 et
